directories:
  output: release
  buildResources: assets
files:
  - filter:
      - build/**/*
      - build/**/*
      - main.js
      - src/preload.js
extraMetadata:
  main: main.js
appId: com.sura.restaurantbilling
productName: SURA Restaurant Billing
win:
  target:
    - nsis
extends: react-cra
electronVersion: 28.3.3
