directories:
  output: dist-electron
  buildResources: assets
files:
  - filter:
      - build/**/*
      - build/**/*
      - main.js
      - src/preload.js
      - node_modules/**/*
      - package.json
extraMetadata:
  main: main.js
appId: com.sura.restaurantbilling
productName: SURA-RESTO by SURA
asarUnpack:
  - '**/electron-log/**'
win:
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  allowElevation: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: SURA-RESTO by SURA
  artifactName: SURA-RESTO-by-SURA-Setup-${version}.exe
portable:
  artifactName: SURA-RESTO-by-SURA-${version}-portable.exe
compression: store
removePackageScripts: true
afterSign: null
afterAllArtifactBuild: null
forceCodeSigning: false
buildDependenciesFromSource: false
extends: react-cra
electronVersion: 28.3.3
